services:
  - type: web
    name: test-personalidad
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: SENDGRID_API_KEY
        value: TU_CLAVE_DE_SENDGRIDhttps://api.render.com/deploy/srv-d0bjrcbuibrs73ddv6ag?key=jag2VQ3i2hw
